= Alpine Theia
An opiniated Alpine Linux-based Theia installation

== Alpine Theia

An opinionated build of the Theia IDE running on Alpine Linux.  This particular instance is designed to develop NodeJS projects. In addition, the build assumes that you will persist all your work externally in a Git project. That is, the image does not mount any local volumes.

=== Run It!

[source,bash]
----
docker run -p 3000:3000 -d --init --mount type=bind,source=<YOUR PROJECT DIR>,target=/home/project --mount type=bind,source=<YOUR SSH KEYS DIR>,target=/home/ssh-keys,readonly wmudge/alpine-theia-nodejs
----

And then open `http://localhost:3000` in your favorite browser.

=== Build Your Own

To build your own Theia version, first clone and then edit the `theia-package.json` file to include the appropriate Theia packages. Then build the Docker image:

[source,bash]
----
docker build -t <your image name> Alpine-Theia
----

Run as above in <<Run It!>>

==== Building on Windows 10

I had some trouble building the image on Win10. I had to make the following adjustments.

I had to turn off the CRLF conversion when cloning the repo. The Windows line termination characters were copied to the Alpine container from the Windows host, and thus the bootstrap script would not execute properly.

[source,bash]
----
git --config auto.crlf=false git@github.com:wmudge/Alpine-Theia.git
----

Node was running out of memory, so I had to add the following before the main `RUN` directive in the Dockerfile:

[source, dockerfile]
----
ENV NODE_OPTIONS=--max-old-space-size=2048
----

=== Setting up Git

You will need to either create or add an existing SSH key within the image for connecting to GitHub (or other Git services). The image contains `openssh-client`, so you can use `ssh-keygen` in a Terminal to create a new key.

The image also has `ssh-agent` set to run prior to the Theia server execution, so you can add your key to the agent with `ssh-add` from a Terminal. If you use the `/home/ssh-keys` bind point, you can use your host's SSH keys.

You will also need to set your Git credentials in a Terminal:

[source,bash]
----
git config --global user.name <your name>
git config --global user.email <your email>
----

Once you have done both, you should commit these changes to your image. See <<Commit Changes>>.

=== Update the Shell

The Alpine installation is pretty barebones, so you might want to add more packages. Check out the https://pkgs.alpinelinux.org/packages?name=&branch=edge[Alpine Package] search page.

=== Commit Changes

Any changes you have made to your image, such as git configuration updates, SSH keys, or package managements, you will need to update the image. Simply execute the following:

[source,bash]
----
docker commit <container id>
----

Note that local storage will be destroyed if the image is stopped (but not paused), so take appropriate actions to save your work if you don't push to a Git project or store it on the host via the bind mounts.
